import { useEffect, useMemo, useState } from "react";
import {
  roadmapMilestones as seededRoadmapMilestones,
  roadmapPhases as seededRoadmapPhases,
  roadmapStats as seededRoadmapStats,
} from "@/data/roadmapData";

export type CmsCollection =
  | "siteStats"
  | "events"
  | "eventRegistrations"
  | "paymentProofs"
  | "tractionStats"
  | "roadmapStats"
  | "roadmapPhases"
  | "roadmapMilestones"
  | "teamCategories"
  | "teamMembers"
  | "partners"
  | "sponsors"
  | "mediaCategories"
  | "mediaPosts"
  | "pages"
  | "contactLeads"
  | "studentProfiles"
  | "certificates"
  | "notifications"
  | "submissions"
  | "settings";

export type CmsItem = Record<string, unknown> & {
  id: string;
  title?: string;
  name?: string;
  active?: boolean;
  order?: number;
};

export const cmsEventName = "innotech-cms-change";

const cmsKey = (collection: CmsCollection) => `innotech-cms-${collection}`;

function canUseStorage() {
  return typeof window !== "undefined" && typeof window.localStorage !== "undefined";
}

export function slugify(value: string) {
  return value
    .toLowerCase()
    .trim()
    .replace(/&/g, "and")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

const now = "2026-05-14";

export const cmsSeed: Record<CmsCollection, CmsItem[]> = {
  siteStats: [
    { id: "revenue-generated", title: "Revenue Generated", value: 2.4, prefix: "₹", suffix: " Lakhs+", shortLabel: "Revenue Generated", description: "Revenue generated by InnoTech-Hub", icon: "Wallet", order: 1, active: true },
    { id: "events-conducted", title: "Events Conducted", value: 7, prefix: "", suffix: "+", shortLabel: "Events Conducted", description: "Official events conducted", icon: "Calendar", order: 2, active: true },
    { id: "hackathon-collaboration", title: "Hackathon Collaboration", value: 1, prefix: "", suffix: "", shortLabel: "Hackathon Collaboration", description: "Hackathon collaboration count", icon: "Trophy", order: 3, active: true },
    { id: "participants-reached", title: "Participants Reached", value: 3000, prefix: "", suffix: "+", shortLabel: "Participants Reached", description: "Students and participants reached", icon: "Users", order: 4, active: true },
    { id: "states-represented", title: "States Represented", value: 8, prefix: "", suffix: "+", shortLabel: "States Represented", description: "States represented by community members", icon: "MapPin", order: 5, active: true },
    { id: "colleges-connected", title: "Colleges Connected", value: 25, prefix: "", suffix: "+", shortLabel: "Colleges Connected", description: "Colleges connected with InnoTech-Hub", icon: "School", order: 6, active: true },
    { id: "growth-note", title: "Growth Text", value: "+24% growth", shortLabel: "Growth Text", description: "Supporting growth note in hero", icon: "Activity", order: 7, active: true },
    { id: "hackathon-note", title: "Hackathon Note", value: "1 hackathon with Gemini Google", shortLabel: "Hackathon Note", description: "Supporting hackathon note in hero", icon: "Trophy", order: 8, active: true },
    { id: "saas-note", title: "SaaS Shipping Note", value: "SaaS shipping", shortLabel: "SaaS Shipping Note", description: "Supporting SaaS note in hero", icon: "Rocket", order: 9, active: true },
  ],
  events: [
    {
      id: "evt-ai-hackathon-challenge",
      title: "AI Hackathon Challenge",
      slug: "ai-hackathon-challenge",
      category: "Hackathons",
      type: "Hybrid",
      participationMode: "Team",
      shortDescription: "A practical AI hackathon focused on useful student-first innovation ideas.",
      fullDescription: "Build, present, and validate an AI-powered solution with guidance from the InnoTech-Hub ecosystem.",
      organizerName: "InnoTech-Hub",
      organizerLogo: "",
      hostedBy: "InnoTech-Hub Community",
      externalLink: "",
      status: "Registration Open",
      featured: true,
      active: true,
      order: 1,
      dates: {
        registrationStartDate: "2026-06-01",
        registrationStartTime: "09:00",
        registrationEndDate: "2026-06-25",
        registrationEndTime: "23:59",
        eventStartDate: "2026-06-28",
        eventStartTime: "10:00",
        eventEndDate: "2026-06-29",
        eventEndTime: "18:00",
        resultDate: "2026-07-02",
        resultTime: "18:00",
        timeZone: "Asia/Kolkata",
      },
      location: {
        meetingPlatform: "Google Meet",
        meetingLink: "",
        backupLink: "",
        communityLink: "https://discord.gg/PHh7BRmq",
        venueName: "Hybrid Innovation Lab",
        collegeName: "Partner Campus",
        address: "Hyderabad",
        city: "Hyderabad",
        state: "Telangana",
        pincode: "",
        mapsLink: "",
      },
      media: {
        banner: "",
        poster: "",
        thumbnail: "",
        mobileBanner: "",
      },
      rounds: [
        { id: "round-1", title: "Idea Submission", type: "Submission", description: "Submit your idea and problem statement.", status: "Open", order: 1 },
        { id: "round-2", title: "Final Presentation", type: "Final Presentation", description: "Present your prototype and impact.", status: "Upcoming", order: 2 },
      ],
      rules: {
        eligibility: "Open to students and early builders.",
        regulations: "Follow the code of conduct and submit original work.",
        guidelines: "Teams should submit clear problem, solution, and demo notes.",
        teamSize: "2-4 members",
        submissionFormat: "PDF deck and demo link",
        judgingCriteria: "Innovation, feasibility, clarity, and impact",
        disqualification: "Plagiarism or misconduct may lead to disqualification.",
        conduct: "Be respectful, collaborative, and transparent.",
        notes: "Keep all proof and submission links ready.",
        documents: "College ID if applicable",
      },
      rewards: {
        totalPrizePool: "₹25,000",
        winnerPrize: "₹12,000",
        runnerUpPrize: "₹8,000",
        secondRunnerUpPrize: "₹5,000",
        specialPrizes: "Community choice recognition",
        certificates: "Participation, Winner, Completion",
        goodies: "Selected goodies for finalists",
        internship: "Possible internship referrals",
        mentorship: "Mentorship for selected teams",
        sponsorRewards: "Sponsor visibility rewards",
        benefits: "Portfolio-ready project and certificate",
      },
      contact: {
        name: "InnoTech-Hub Support",
        role: "Event Team",
        email: "innotechhub@gmail.com",
        phone: "",
        whatsapp: "",
        discord: "https://discord.gg/PHh7BRmq",
        telegram: "",
        message: "Reach out for registration and payment queries.",
      },
      payment: {
        type: "Paid Event",
        amount: 299,
        currency: "INR",
        upiId: "innotechhub@upi",
        qrImage: "",
        instructions: "Pay using UPI and upload the screenshot with transaction ID.",
        deadline: "2026-06-25",
        refundPolicy: "Refunds are handled case-by-case before registration closes.",
        verificationNote: "Payments are manually verified by the admin team.",
      },
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "evt-resume-building-workshop",
      title: "Resume Building Workshop",
      slug: "resume-building-workshop",
      category: "Workshops",
      type: "Online",
      participationMode: "Individual",
      shortDescription: "A hands-on resume and portfolio readiness workshop for students.",
      fullDescription: "Learn how to turn projects, events, and skills into a stronger resume and profile.",
      organizerName: "InnoTech-Hub",
      hostedBy: "InnoTech-Hub Community",
      status: "Registration Open",
      featured: false,
      active: true,
      order: 2,
      dates: { registrationStartDate: "2026-06-05", registrationStartTime: "09:00", registrationEndDate: "2026-06-20", registrationEndTime: "20:00", eventStartDate: "2026-06-22", eventStartTime: "18:00", eventEndDate: "2026-06-22", eventEndTime: "20:00", resultDate: "", resultTime: "", timeZone: "Asia/Kolkata" },
      location: { meetingPlatform: "Google Meet", meetingLink: "", backupLink: "", communityLink: "https://discord.gg/PHh7BRmq" },
      media: { banner: "", poster: "", thumbnail: "", mobileBanner: "" },
      rounds: [],
      rules: { eligibility: "Open to students.", regulations: "Attend on time.", guidelines: "Keep your current resume ready.", teamSize: "Individual", submissionFormat: "Resume PDF", judgingCriteria: "", disqualification: "", conduct: "Respect the session flow.", notes: "", documents: "" },
      rewards: { totalPrizePool: "", winnerPrize: "", runnerUpPrize: "", secondRunnerUpPrize: "", specialPrizes: "", certificates: "Completion certificate", goodies: "", internship: "", mentorship: "Resume review guidance", sponsorRewards: "", benefits: "Improved resume and profile clarity" },
      contact: { name: "InnoTech-Hub Support", role: "Workshop Team", email: "innotechhub@gmail.com", phone: "", whatsapp: "", discord: "https://discord.gg/PHh7BRmq", telegram: "", message: "Join the community link for updates." },
      payment: { type: "Free Event", amount: 0, currency: "INR", upiId: "", qrImage: "", instructions: "", deadline: "", refundPolicy: "", verificationNote: "" },
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "evt-tech-podcast-live-session",
      title: "Tech Podcast Live Session",
      slug: "tech-podcast-live-session",
      category: "Tech Podcasts",
      type: "Online",
      participationMode: "Individual",
      shortDescription: "A live student-first conversation with builders and achievers.",
      fullDescription: "Hear practical stories from tech achievers and learn how to build momentum as a student.",
      organizerName: "InnoTech-Hub",
      hostedBy: "InnoTech-Hub Media",
      status: "Published",
      featured: false,
      active: true,
      order: 3,
      dates: { registrationStartDate: "2026-07-01", registrationStartTime: "09:00", registrationEndDate: "2026-07-14", registrationEndTime: "20:00", eventStartDate: "2026-07-15", eventStartTime: "19:00", eventEndDate: "2026-07-15", eventEndTime: "20:00", resultDate: "", resultTime: "", timeZone: "Asia/Kolkata" },
      location: { meetingPlatform: "YouTube Live", meetingLink: "", backupLink: "", communityLink: "https://discord.gg/PHh7BRmq" },
      media: { banner: "", poster: "", thumbnail: "", mobileBanner: "" },
      rounds: [],
      rules: { eligibility: "Open to all students.", regulations: "Respect the speaker and audience.", guidelines: "Bring questions.", teamSize: "Individual", submissionFormat: "", judgingCriteria: "", disqualification: "", conduct: "Keep chat respectful.", notes: "", documents: "" },
      rewards: { totalPrizePool: "", winnerPrize: "", runnerUpPrize: "", secondRunnerUpPrize: "", specialPrizes: "", certificates: "Participation certificate", goodies: "", internship: "", mentorship: "", sponsorRewards: "", benefits: "Student growth insights" },
      contact: { name: "InnoTech-Hub Support", role: "Media Team", email: "innotechhub@gmail.com", phone: "", whatsapp: "", discord: "https://discord.gg/PHh7BRmq", telegram: "", message: "Session details will be shared before the event." },
      payment: { type: "Free Event", amount: 0, currency: "INR", upiId: "", qrImage: "", instructions: "", deadline: "", refundPolicy: "", verificationNote: "" },
      createdAt: now,
      updatedAt: now,
    },
  ],
  eventRegistrations: [],
  paymentProofs: [],
  tractionStats: [
    { id: "traction-revenue", sectionLabel: "Business Model", sectionHeading: "Current Traction", title: "Revenue Generated", value: 2.4, prefix: "₹", suffix: " Lakhs+", description: "Revenue generated", order: 1, active: true },
    { id: "traction-events", sectionLabel: "Business Model", sectionHeading: "Current Traction", title: "Tech & Non-Tech Events", value: 7, prefix: "", suffix: "+", description: "Events completed", order: 2, active: true },
    { id: "traction-hackathon", sectionLabel: "Business Model", sectionHeading: "Current Traction", title: "Hackathon with Gemini Google", value: 1, prefix: "", suffix: "", description: "Hackathon collaboration", order: 3, active: true },
    { id: "traction-participants", sectionLabel: "Business Model", sectionHeading: "Current Traction", title: "Participants Reached", value: 3000, prefix: "", suffix: "+", description: "Participants reached", order: 4, active: true },
    { id: "traction-states", sectionLabel: "Business Model", sectionHeading: "Current Traction", title: "States Represented", value: 8, prefix: "", suffix: "+", description: "States represented", order: 5, active: true },
    { id: "traction-colleges", sectionLabel: "Business Model", sectionHeading: "Current Traction", title: "Colleges Connected", value: 25, prefix: "", suffix: "+", description: "Colleges connected", order: 6, active: true },
  ],
  roadmapStats: seededRoadmapStats.map((item, index) => ({ ...item, id: slugify(item.title), order: index + 1, active: true })),
  roadmapPhases: seededRoadmapPhases.map((item, index) => ({ ...item, code: item.id, id: item.id.toLowerCase(), description: "", order: index + 1, active: true })),
  roadmapMilestones: seededRoadmapMilestones.map((item, index) => ({ ...item, timeline: item.quarter, id: slugify(`${item.quarter}-${item.title}`), description: "", order: index + 1, active: true })),
  teamCategories: [
    { id: "founders-core", name: "Founders / Core Team", slug: "founders-core", shortDescription: "Driven contributors building, shipping, and scaling InnoTech-Hub every day.", icon: "Users", order: 1, active: true },
    { id: "event-operations", name: "Event Operations", slug: "event-operations", shortDescription: "Driven contributors building, shipping, and scaling InnoTech-Hub every day.", icon: "Users", order: 2, active: true },
    { id: "tech-product", name: "Tech & Product", slug: "tech-product", shortDescription: "Driven contributors building, shipping, and scaling InnoTech-Hub every day.", icon: "Users", order: 3, active: true },
    { id: "design-media", name: "Design & Media", slug: "design-media", shortDescription: "Driven contributors building, shipping, and scaling InnoTech-Hub every day.", icon: "Users", order: 4, active: true },
    { id: "community", name: "Community", slug: "community", shortDescription: "Driven contributors building, shipping, and scaling InnoTech-Hub every day.", icon: "Users", order: 5, active: true },
    { id: "partnerships", name: "Partnerships", slug: "partnerships", shortDescription: "Driven contributors building, shipping, and scaling InnoTech-Hub every day.", icon: "Users", order: 6, active: true },
  ],
  teamMembers: [],
  partners: Array.from({ length: 12 }).map((_, index) => ({
    id: `partner-${index + 1}`,
    name: `PARTNER ${index + 1}`,
    websiteUrl: "",
    shortDescription: "",
    category: "Partner",
    contactPerson: "",
    contactEmail: "",
    logoUrl: "",
    order: index + 1,
    active: true,
  })),
  sponsors: [],
  mediaCategories: [
    "Event Highlights",
    "Student Testimonials",
    "Podcast Clips",
    "Hackathon Stories",
    "Tech Fest Moments",
    "Partner Shoutouts",
  ].map((name, index) => ({ id: slugify(name), name, slug: slugify(name), shortDescription: "", order: index + 1, active: true })),
  mediaPosts: [],
  pages: [
    {
      id: "privacy-policy",
      title: "Privacy Policy",
      slug: "privacy-policy",
      content: "Information collected\nLogin/signup data\nEvent registration data\nContact form data\nStudent dashboard data\nCookies/analytics\nHow data is used\nThird-party services such as Google login, Vercel, storage, analytics\nData security\nUser rights\nContact email",
      lastUpdated: now,
      active: true,
      order: 1,
    },
    {
      id: "terms",
      title: "Terms & Conditions",
      slug: "terms",
      content: "Platform usage rules\nEvent participation rules\nAccount responsibilities\nPayment/refund basics\nCertificate conditions\nProhibited activities\nLimitation of liability\nContact details",
      lastUpdated: now,
      active: true,
      order: 2,
    },
    {
      id: "rules",
      title: "Rules & Regulations",
      slug: "rules",
      content: "Event conduct\nHackathon/workshop rules\nPayment proof rules\nTeam rules\nSubmission rules\nDisqualification rules\nCode of conduct",
      lastUpdated: now,
      active: true,
      order: 3,
    },
  ],
  contactLeads: [],
  studentProfiles: [],
  certificates: [],
  notifications: [],
  submissions: [],
  settings: [
    { id: "site", websiteName: "InnoTech-Hub", contactEmail: "innotechhub@gmail.com", socialLinks: "", active: true },
  ],
};

export function sortActive<T extends CmsItem>(items: T[]) {
  return [...items]
    .filter((item) => item.active !== false)
    .sort((a, b) => Number(a.order ?? 0) - Number(b.order ?? 0));
}

export function getCmsCollection<T extends CmsItem = CmsItem>(collection: CmsCollection): T[] {
  if (!canUseStorage()) return cmsSeed[collection] as T[];

  try {
    const raw = window.localStorage.getItem(cmsKey(collection));
    if (!raw) return cmsSeed[collection] as T[];
    const parsed = JSON.parse(raw);
    return Array.isArray(parsed) ? parsed.filter((item) => item && typeof item === "object") : (cmsSeed[collection] as T[]);
  } catch (error) {
    console.error(`Unable to read ${collection} from localStorage`, error);
    return cmsSeed[collection] as T[];
  }
}

export function saveCmsCollection<T extends CmsItem>(collection: CmsCollection, items: T[]) {
  if (!canUseStorage()) return;
  try {
    window.localStorage.setItem(cmsKey(collection), JSON.stringify(items));
    window.dispatchEvent(new CustomEvent(cmsEventName, { detail: { collection } }));
  } catch (error) {
    console.error(`Unable to save ${collection} to localStorage`, error);
    window.dispatchEvent(new CustomEvent(cmsEventName, { detail: { collection, error } }));
  }
}

export function useCmsCollection<T extends CmsItem = CmsItem>(collection: CmsCollection) {
  const [items, setItems] = useState<T[]>(() => getCmsCollection<T>(collection));

  useEffect(() => {
    const sync = () => setItems(getCmsCollection<T>(collection));
    sync();
    window.addEventListener("storage", sync);
    window.addEventListener(cmsEventName, sync);
    return () => {
      window.removeEventListener("storage", sync);
      window.removeEventListener(cmsEventName, sync);
    };
  }, [collection]);

  const activeItems = useMemo(() => sortActive(items), [items]);

  return { items, activeItems, setItems: (next: T[]) => saveCmsCollection(collection, next) };
}

export function upsertCmsItem<T extends CmsItem>(items: T[], item: T) {
  const exists = items.some((current) => current.id === item.id);
  return exists ? items.map((current) => (current.id === item.id ? item : current)) : [...items, item];
}
