import { useEffect, useMemo, useState } from "react";
import {
  roadmapMilestones as seededRoadmapMilestones,
  roadmapPhases as seededRoadmapPhases,
  roadmapStats as seededRoadmapStats,
} from "@/data/roadmapData";

export type CmsCollection =
  | "siteStats"
  | "events"
  | "tractionStats"
  | "roadmapStats"
  | "roadmapPhases"
  | "roadmapMilestones"
  | "teamCategories"
  | "teamMembers"
  | "partners"
  | "sponsors"
  | "mediaCategories"
  | "mediaPosts"
  | "pages"
  | "contactLeads"
  | "settings";

export type CmsItem = Record<string, unknown> & {
  id: string;
  title?: string;
  name?: string;
  active?: boolean;
  order?: number;
};

export const cmsEventName = "innotech-cms-change";

const cmsKey = (collection: CmsCollection) => `innotech-cms-${collection}`;

function canUseStorage() {
  return typeof window !== "undefined" && typeof window.localStorage !== "undefined";
}

export function slugify(value: string) {
  return value
    .toLowerCase()
    .trim()
    .replace(/&/g, "and")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

const now = "2026-05-14";

export const cmsSeed: Record<CmsCollection, CmsItem[]> = {
  siteStats: [
    { id: "revenue-generated", title: "Revenue Generated", value: 2.4, prefix: "₹", suffix: " Lakhs+", shortLabel: "Revenue Generated", description: "Revenue generated by InnoTech-Hub", icon: "Wallet", order: 1, active: true },
    { id: "events-conducted", title: "Events Conducted", value: 7, prefix: "", suffix: "+", shortLabel: "Events Conducted", description: "Official events conducted", icon: "Calendar", order: 2, active: true },
    { id: "hackathon-collaboration", title: "Hackathon Collaboration", value: 1, prefix: "", suffix: "", shortLabel: "Hackathon Collaboration", description: "Hackathon collaboration count", icon: "Trophy", order: 3, active: true },
    { id: "participants-reached", title: "Participants Reached", value: 3000, prefix: "", suffix: "+", shortLabel: "Participants Reached", description: "Students and participants reached", icon: "Users", order: 4, active: true },
    { id: "states-represented", title: "States Represented", value: 8, prefix: "", suffix: "+", shortLabel: "States Represented", description: "States represented by community members", icon: "MapPin", order: 5, active: true },
    { id: "colleges-connected", title: "Colleges Connected", value: 25, prefix: "", suffix: "+", shortLabel: "Colleges Connected", description: "Colleges connected with InnoTech-Hub", icon: "School", order: 6, active: true },
    { id: "growth-note", title: "Growth Text", value: "+24% growth", shortLabel: "Growth Text", description: "Supporting growth note in hero", icon: "Activity", order: 7, active: true },
    { id: "hackathon-note", title: "Hackathon Note", value: "1 hackathon with Gemini Google", shortLabel: "Hackathon Note", description: "Supporting hackathon note in hero", icon: "Trophy", order: 8, active: true },
    { id: "saas-note", title: "SaaS Shipping Note", value: "SaaS shipping", shortLabel: "SaaS Shipping Note", description: "Supporting SaaS note in hero", icon: "Rocket", order: 9, active: true },
  ],
  events: [],
  tractionStats: [
    { id: "traction-revenue", sectionLabel: "Business Model", sectionHeading: "Current Traction", title: "Revenue Generated", value: 2.4, prefix: "₹", suffix: " Lakhs+", description: "Revenue generated", order: 1, active: true },
    { id: "traction-events", sectionLabel: "Business Model", sectionHeading: "Current Traction", title: "Tech & Non-Tech Events", value: 7, prefix: "", suffix: "+", description: "Events completed", order: 2, active: true },
    { id: "traction-hackathon", sectionLabel: "Business Model", sectionHeading: "Current Traction", title: "Hackathon with Gemini Google", value: 1, prefix: "", suffix: "", description: "Hackathon collaboration", order: 3, active: true },
    { id: "traction-participants", sectionLabel: "Business Model", sectionHeading: "Current Traction", title: "Participants Reached", value: 3000, prefix: "", suffix: "+", description: "Participants reached", order: 4, active: true },
    { id: "traction-states", sectionLabel: "Business Model", sectionHeading: "Current Traction", title: "States Represented", value: 8, prefix: "", suffix: "+", description: "States represented", order: 5, active: true },
    { id: "traction-colleges", sectionLabel: "Business Model", sectionHeading: "Current Traction", title: "Colleges Connected", value: 25, prefix: "", suffix: "+", description: "Colleges connected", order: 6, active: true },
  ],
  roadmapStats: seededRoadmapStats.map((item, index) => ({ ...item, id: slugify(item.title), order: index + 1, active: true })),
  roadmapPhases: seededRoadmapPhases.map((item, index) => ({ ...item, code: item.id, id: item.id.toLowerCase(), description: "", order: index + 1, active: true })),
  roadmapMilestones: seededRoadmapMilestones.map((item, index) => ({ ...item, timeline: item.quarter, id: slugify(`${item.quarter}-${item.title}`), description: "", order: index + 1, active: true })),
  teamCategories: [
    { id: "founders-core", name: "Founders / Core Team", slug: "founders-core", shortDescription: "Driven contributors building, shipping, and scaling InnoTech-Hub every day.", icon: "Users", order: 1, active: true },
    { id: "event-operations", name: "Event Operations", slug: "event-operations", shortDescription: "Driven contributors building, shipping, and scaling InnoTech-Hub every day.", icon: "Users", order: 2, active: true },
    { id: "tech-product", name: "Tech & Product", slug: "tech-product", shortDescription: "Driven contributors building, shipping, and scaling InnoTech-Hub every day.", icon: "Users", order: 3, active: true },
    { id: "design-media", name: "Design & Media", slug: "design-media", shortDescription: "Driven contributors building, shipping, and scaling InnoTech-Hub every day.", icon: "Users", order: 4, active: true },
    { id: "community", name: "Community", slug: "community", shortDescription: "Driven contributors building, shipping, and scaling InnoTech-Hub every day.", icon: "Users", order: 5, active: true },
    { id: "partnerships", name: "Partnerships", slug: "partnerships", shortDescription: "Driven contributors building, shipping, and scaling InnoTech-Hub every day.", icon: "Users", order: 6, active: true },
  ],
  teamMembers: [],
  partners: Array.from({ length: 12 }).map((_, index) => ({
    id: `partner-${index + 1}`,
    name: `PARTNER ${index + 1}`,
    websiteUrl: "",
    shortDescription: "",
    category: "Partner",
    contactPerson: "",
    contactEmail: "",
    logoUrl: "",
    order: index + 1,
    active: true,
  })),
  sponsors: [],
  mediaCategories: [
    "Event Highlights",
    "Student Testimonials",
    "Podcast Clips",
    "Hackathon Stories",
    "Tech Fest Moments",
    "Partner Shoutouts",
  ].map((name, index) => ({ id: slugify(name), name, slug: slugify(name), shortDescription: "", order: index + 1, active: true })),
  mediaPosts: [],
  pages: [
    {
      id: "privacy-policy",
      title: "Privacy Policy",
      slug: "privacy-policy",
      content: "Information collected\nLogin/signup data\nEvent registration data\nContact form data\nStudent dashboard data\nCookies/analytics\nHow data is used\nThird-party services such as Google login, Vercel, storage, analytics\nData security\nUser rights\nContact email",
      lastUpdated: now,
      active: true,
      order: 1,
    },
    {
      id: "terms",
      title: "Terms & Conditions",
      slug: "terms",
      content: "Platform usage rules\nEvent participation rules\nAccount responsibilities\nPayment/refund basics\nCertificate conditions\nProhibited activities\nLimitation of liability\nContact details",
      lastUpdated: now,
      active: true,
      order: 2,
    },
    {
      id: "rules",
      title: "Rules & Regulations",
      slug: "rules",
      content: "Event conduct\nHackathon/workshop rules\nPayment proof rules\nTeam rules\nSubmission rules\nDisqualification rules\nCode of conduct",
      lastUpdated: now,
      active: true,
      order: 3,
    },
  ],
  contactLeads: [],
  settings: [
    { id: "site", websiteName: "InnoTech-Hub", contactEmail: "innotechhub@gmail.com", socialLinks: "", active: true },
  ],
};

export function sortActive<T extends CmsItem>(items: T[]) {
  return [...items]
    .filter((item) => item.active !== false)
    .sort((a, b) => Number(a.order ?? 0) - Number(b.order ?? 0));
}

export function getCmsCollection<T extends CmsItem = CmsItem>(collection: CmsCollection): T[] {
  if (!canUseStorage()) return cmsSeed[collection] as T[];

  try {
    const raw = window.localStorage.getItem(cmsKey(collection));
    return raw ? JSON.parse(raw) : (cmsSeed[collection] as T[]);
  } catch {
    return cmsSeed[collection] as T[];
  }
}

export function saveCmsCollection<T extends CmsItem>(collection: CmsCollection, items: T[]) {
  if (!canUseStorage()) return;
  window.localStorage.setItem(cmsKey(collection), JSON.stringify(items));
  window.dispatchEvent(new CustomEvent(cmsEventName, { detail: { collection } }));
}

export function useCmsCollection<T extends CmsItem = CmsItem>(collection: CmsCollection) {
  const [items, setItems] = useState<T[]>(() => getCmsCollection<T>(collection));

  useEffect(() => {
    const sync = () => setItems(getCmsCollection<T>(collection));
    sync();
    window.addEventListener("storage", sync);
    window.addEventListener(cmsEventName, sync);
    return () => {
      window.removeEventListener("storage", sync);
      window.removeEventListener(cmsEventName, sync);
    };
  }, [collection]);

  const activeItems = useMemo(() => sortActive(items), [items]);

  return { items, activeItems, setItems: (next: T[]) => saveCmsCollection(collection, next) };
}

export function upsertCmsItem<T extends CmsItem>(items: T[], item: T) {
  const exists = items.some((current) => current.id === item.id);
  return exists ? items.map((current) => (current.id === item.id ? item : current)) : [...items, item];
}
