/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as MediaRouteImport } from './routes/media'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EventsRouteImport } from './routes/events'
import { Route as EventPlatformRouteImport } from './routes/event-platform'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamSlugRouteImport } from './routes/team/$slug'
import { Route as StudentSettingsRouteImport } from './routes/student/settings'
import { Route as StudentRegistrationsRouteImport } from './routes/student/registrations'
import { Route as StudentProfileRouteImport } from './routes/student/profile'
import { Route as StudentEventsRouteImport } from './routes/student/events'
import { Route as StudentDashboardRouteImport } from './routes/student/dashboard'
import { Route as MediaSlugRouteImport } from './routes/media/$slug'
import { Route as EventsSlugRouteImport } from './routes/events/$slug'
import { Route as AdminTractionRouteImport } from './routes/admin/traction'
import { Route as AdminTeamRouteImport } from './routes/admin/team'
import { Route as AdminSponsorsRouteImport } from './routes/admin/sponsors'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminRoadmapRouteImport } from './routes/admin/roadmap'
import { Route as AdminPaymentsRouteImport } from './routes/admin/payments'
import { Route as AdminPartnersRouteImport } from './routes/admin/partners'
import { Route as AdminPagesRouteImport } from './routes/admin/pages'
import { Route as AdminMediaRouteImport } from './routes/admin/media'
import { Route as AdminEventsRouteImport } from './routes/admin/events'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminContactLeadsRouteImport } from './routes/admin/contact-leads'
import { Route as EventsSlugRegisterRouteImport } from './routes/events/$slug/register'
import { Route as AdminEventsEventIdRegistrationsRouteImport } from './routes/admin/events/$eventId/registrations'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const EventPlatformRoute = EventPlatformRouteImport.update({
  id: '/event-platform',
  path: '/event-platform',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamSlugRoute = TeamSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TeamRoute,
} as any)
const StudentSettingsRoute = StudentSettingsRouteImport.update({
  id: '/student/settings',
  path: '/student/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRegistrationsRoute = StudentRegistrationsRouteImport.update({
  id: '/student/registrations',
  path: '/student/registrations',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/student/profile',
  path: '/student/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentEventsRoute = StudentEventsRouteImport.update({
  id: '/student/events',
  path: '/student/events',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/student/dashboard',
  path: '/student/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaSlugRoute = MediaSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => MediaRoute,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EventsRoute,
} as any)
const AdminTractionRoute = AdminTractionRouteImport.update({
  id: '/admin/traction',
  path: '/admin/traction',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeamRoute = AdminTeamRouteImport.update({
  id: '/admin/team',
  path: '/admin/team',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSponsorsRoute = AdminSponsorsRouteImport.update({
  id: '/admin/sponsors',
  path: '/admin/sponsors',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoadmapRoute = AdminRoadmapRouteImport.update({
  id: '/admin/roadmap',
  path: '/admin/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/admin/payments',
  path: '/admin/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPartnersRoute = AdminPartnersRouteImport.update({
  id: '/admin/partners',
  path: '/admin/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPagesRoute = AdminPagesRouteImport.update({
  id: '/admin/pages',
  path: '/admin/pages',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/admin/media',
  path: '/admin/media',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/admin/events',
  path: '/admin/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContactLeadsRoute = AdminContactLeadsRouteImport.update({
  id: '/admin/contact-leads',
  path: '/admin/contact-leads',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsSlugRegisterRoute = EventsSlugRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => EventsSlugRoute,
} as any)
const AdminEventsEventIdRegistrationsRoute =
  AdminEventsEventIdRegistrationsRouteImport.update({
    id: '/$eventId/registrations',
    path: '/$eventId/registrations',
    getParentRoute: () => AdminEventsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/event-platform': typeof EventPlatformRoute
  '/events': typeof EventsRouteWithChildren
  '/login': typeof LoginRoute
  '/media': typeof MediaRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/roadmap': typeof RoadmapRoute
  '/rules': typeof RulesRoute
  '/signup': typeof SignupRoute
  '/team': typeof TeamRouteWithChildren
  '/terms': typeof TermsRoute
  '/admin/contact-leads': typeof AdminContactLeadsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/events': typeof AdminEventsRouteWithChildren
  '/admin/media': typeof AdminMediaRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/roadmap': typeof AdminRoadmapRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sponsors': typeof AdminSponsorsRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/traction': typeof AdminTractionRoute
  '/events/$slug': typeof EventsSlugRouteWithChildren
  '/media/$slug': typeof MediaSlugRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/events': typeof StudentEventsRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/registrations': typeof StudentRegistrationsRoute
  '/student/settings': typeof StudentSettingsRoute
  '/team/$slug': typeof TeamSlugRoute
  '/events/$slug/register': typeof EventsSlugRegisterRoute
  '/admin/events/$eventId/registrations': typeof AdminEventsEventIdRegistrationsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/event-platform': typeof EventPlatformRoute
  '/events': typeof EventsRouteWithChildren
  '/login': typeof LoginRoute
  '/media': typeof MediaRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/roadmap': typeof RoadmapRoute
  '/rules': typeof RulesRoute
  '/signup': typeof SignupRoute
  '/team': typeof TeamRouteWithChildren
  '/terms': typeof TermsRoute
  '/admin/contact-leads': typeof AdminContactLeadsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/events': typeof AdminEventsRouteWithChildren
  '/admin/media': typeof AdminMediaRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/roadmap': typeof AdminRoadmapRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sponsors': typeof AdminSponsorsRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/traction': typeof AdminTractionRoute
  '/events/$slug': typeof EventsSlugRouteWithChildren
  '/media/$slug': typeof MediaSlugRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/events': typeof StudentEventsRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/registrations': typeof StudentRegistrationsRoute
  '/student/settings': typeof StudentSettingsRoute
  '/team/$slug': typeof TeamSlugRoute
  '/events/$slug/register': typeof EventsSlugRegisterRoute
  '/admin/events/$eventId/registrations': typeof AdminEventsEventIdRegistrationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/event-platform': typeof EventPlatformRoute
  '/events': typeof EventsRouteWithChildren
  '/login': typeof LoginRoute
  '/media': typeof MediaRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/roadmap': typeof RoadmapRoute
  '/rules': typeof RulesRoute
  '/signup': typeof SignupRoute
  '/team': typeof TeamRouteWithChildren
  '/terms': typeof TermsRoute
  '/admin/contact-leads': typeof AdminContactLeadsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/events': typeof AdminEventsRouteWithChildren
  '/admin/media': typeof AdminMediaRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/roadmap': typeof AdminRoadmapRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sponsors': typeof AdminSponsorsRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/traction': typeof AdminTractionRoute
  '/events/$slug': typeof EventsSlugRouteWithChildren
  '/media/$slug': typeof MediaSlugRoute
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/events': typeof StudentEventsRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/registrations': typeof StudentRegistrationsRoute
  '/student/settings': typeof StudentSettingsRoute
  '/team/$slug': typeof TeamSlugRoute
  '/events/$slug/register': typeof EventsSlugRegisterRoute
  '/admin/events/$eventId/registrations': typeof AdminEventsEventIdRegistrationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contact'
    | '/event-platform'
    | '/events'
    | '/login'
    | '/media'
    | '/pricing'
    | '/privacy-policy'
    | '/roadmap'
    | '/rules'
    | '/signup'
    | '/team'
    | '/terms'
    | '/admin/contact-leads'
    | '/admin/dashboard'
    | '/admin/events'
    | '/admin/media'
    | '/admin/pages'
    | '/admin/partners'
    | '/admin/payments'
    | '/admin/roadmap'
    | '/admin/settings'
    | '/admin/sponsors'
    | '/admin/team'
    | '/admin/traction'
    | '/events/$slug'
    | '/media/$slug'
    | '/student/dashboard'
    | '/student/events'
    | '/student/profile'
    | '/student/registrations'
    | '/student/settings'
    | '/team/$slug'
    | '/events/$slug/register'
    | '/admin/events/$eventId/registrations'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contact'
    | '/event-platform'
    | '/events'
    | '/login'
    | '/media'
    | '/pricing'
    | '/privacy-policy'
    | '/roadmap'
    | '/rules'
    | '/signup'
    | '/team'
    | '/terms'
    | '/admin/contact-leads'
    | '/admin/dashboard'
    | '/admin/events'
    | '/admin/media'
    | '/admin/pages'
    | '/admin/partners'
    | '/admin/payments'
    | '/admin/roadmap'
    | '/admin/settings'
    | '/admin/sponsors'
    | '/admin/team'
    | '/admin/traction'
    | '/events/$slug'
    | '/media/$slug'
    | '/student/dashboard'
    | '/student/events'
    | '/student/profile'
    | '/student/registrations'
    | '/student/settings'
    | '/team/$slug'
    | '/events/$slug/register'
    | '/admin/events/$eventId/registrations'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/contact'
    | '/event-platform'
    | '/events'
    | '/login'
    | '/media'
    | '/pricing'
    | '/privacy-policy'
    | '/roadmap'
    | '/rules'
    | '/signup'
    | '/team'
    | '/terms'
    | '/admin/contact-leads'
    | '/admin/dashboard'
    | '/admin/events'
    | '/admin/media'
    | '/admin/pages'
    | '/admin/partners'
    | '/admin/payments'
    | '/admin/roadmap'
    | '/admin/settings'
    | '/admin/sponsors'
    | '/admin/team'
    | '/admin/traction'
    | '/events/$slug'
    | '/media/$slug'
    | '/student/dashboard'
    | '/student/events'
    | '/student/profile'
    | '/student/registrations'
    | '/student/settings'
    | '/team/$slug'
    | '/events/$slug/register'
    | '/admin/events/$eventId/registrations'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  EventPlatformRoute: typeof EventPlatformRoute
  EventsRoute: typeof EventsRouteWithChildren
  LoginRoute: typeof LoginRoute
  MediaRoute: typeof MediaRouteWithChildren
  PricingRoute: typeof PricingRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RoadmapRoute: typeof RoadmapRoute
  RulesRoute: typeof RulesRoute
  SignupRoute: typeof SignupRoute
  TeamRoute: typeof TeamRouteWithChildren
  TermsRoute: typeof TermsRoute
  AdminContactLeadsRoute: typeof AdminContactLeadsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminEventsRoute: typeof AdminEventsRouteWithChildren
  AdminMediaRoute: typeof AdminMediaRoute
  AdminPagesRoute: typeof AdminPagesRoute
  AdminPartnersRoute: typeof AdminPartnersRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminRoadmapRoute: typeof AdminRoadmapRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSponsorsRoute: typeof AdminSponsorsRoute
  AdminTeamRoute: typeof AdminTeamRoute
  AdminTractionRoute: typeof AdminTractionRoute
  StudentDashboardRoute: typeof StudentDashboardRoute
  StudentEventsRoute: typeof StudentEventsRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentRegistrationsRoute: typeof StudentRegistrationsRoute
  StudentSettingsRoute: typeof StudentSettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event-platform': {
      id: '/event-platform'
      path: '/event-platform'
      fullPath: '/event-platform'
      preLoaderRoute: typeof EventPlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$slug': {
      id: '/team/$slug'
      path: '/$slug'
      fullPath: '/team/$slug'
      preLoaderRoute: typeof TeamSlugRouteImport
      parentRoute: typeof TeamRoute
    }
    '/student/settings': {
      id: '/student/settings'
      path: '/student/settings'
      fullPath: '/student/settings'
      preLoaderRoute: typeof StudentSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/registrations': {
      id: '/student/registrations'
      path: '/student/registrations'
      fullPath: '/student/registrations'
      preLoaderRoute: typeof StudentRegistrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/student/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/events': {
      id: '/student/events'
      path: '/student/events'
      fullPath: '/student/events'
      preLoaderRoute: typeof StudentEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/dashboard': {
      id: '/student/dashboard'
      path: '/student/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/$slug': {
      id: '/media/$slug'
      path: '/$slug'
      fullPath: '/media/$slug'
      preLoaderRoute: typeof MediaSlugRouteImport
      parentRoute: typeof MediaRoute
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof EventsRoute
    }
    '/admin/traction': {
      id: '/admin/traction'
      path: '/admin/traction'
      fullPath: '/admin/traction'
      preLoaderRoute: typeof AdminTractionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/team': {
      id: '/admin/team'
      path: '/admin/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AdminTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sponsors': {
      id: '/admin/sponsors'
      path: '/admin/sponsors'
      fullPath: '/admin/sponsors'
      preLoaderRoute: typeof AdminSponsorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/roadmap': {
      id: '/admin/roadmap'
      path: '/admin/roadmap'
      fullPath: '/admin/roadmap'
      preLoaderRoute: typeof AdminRoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/admin/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/partners': {
      id: '/admin/partners'
      path: '/admin/partners'
      fullPath: '/admin/partners'
      preLoaderRoute: typeof AdminPartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pages': {
      id: '/admin/pages'
      path: '/admin/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AdminPagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/admin/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/admin/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/contact-leads': {
      id: '/admin/contact-leads'
      path: '/admin/contact-leads'
      fullPath: '/admin/contact-leads'
      preLoaderRoute: typeof AdminContactLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$slug/register': {
      id: '/events/$slug/register'
      path: '/register'
      fullPath: '/events/$slug/register'
      preLoaderRoute: typeof EventsSlugRegisterRouteImport
      parentRoute: typeof EventsSlugRoute
    }
    '/admin/events/$eventId/registrations': {
      id: '/admin/events/$eventId/registrations'
      path: '/$eventId/registrations'
      fullPath: '/admin/events/$eventId/registrations'
      preLoaderRoute: typeof AdminEventsEventIdRegistrationsRouteImport
      parentRoute: typeof AdminEventsRoute
    }
  }
}

interface EventsSlugRouteChildren {
  EventsSlugRegisterRoute: typeof EventsSlugRegisterRoute
}

const EventsSlugRouteChildren: EventsSlugRouteChildren = {
  EventsSlugRegisterRoute: EventsSlugRegisterRoute,
}

const EventsSlugRouteWithChildren = EventsSlugRoute._addFileChildren(
  EventsSlugRouteChildren,
)

interface EventsRouteChildren {
  EventsSlugRoute: typeof EventsSlugRouteWithChildren
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsSlugRoute: EventsSlugRouteWithChildren,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

interface MediaRouteChildren {
  MediaSlugRoute: typeof MediaSlugRoute
}

const MediaRouteChildren: MediaRouteChildren = {
  MediaSlugRoute: MediaSlugRoute,
}

const MediaRouteWithChildren = MediaRoute._addFileChildren(MediaRouteChildren)

interface TeamRouteChildren {
  TeamSlugRoute: typeof TeamSlugRoute
}

const TeamRouteChildren: TeamRouteChildren = {
  TeamSlugRoute: TeamSlugRoute,
}

const TeamRouteWithChildren = TeamRoute._addFileChildren(TeamRouteChildren)

interface AdminEventsRouteChildren {
  AdminEventsEventIdRegistrationsRoute: typeof AdminEventsEventIdRegistrationsRoute
}

const AdminEventsRouteChildren: AdminEventsRouteChildren = {
  AdminEventsEventIdRegistrationsRoute: AdminEventsEventIdRegistrationsRoute,
}

const AdminEventsRouteWithChildren = AdminEventsRoute._addFileChildren(
  AdminEventsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  EventPlatformRoute: EventPlatformRoute,
  EventsRoute: EventsRouteWithChildren,
  LoginRoute: LoginRoute,
  MediaRoute: MediaRouteWithChildren,
  PricingRoute: PricingRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RoadmapRoute: RoadmapRoute,
  RulesRoute: RulesRoute,
  SignupRoute: SignupRoute,
  TeamRoute: TeamRouteWithChildren,
  TermsRoute: TermsRoute,
  AdminContactLeadsRoute: AdminContactLeadsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminEventsRoute: AdminEventsRouteWithChildren,
  AdminMediaRoute: AdminMediaRoute,
  AdminPagesRoute: AdminPagesRoute,
  AdminPartnersRoute: AdminPartnersRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminRoadmapRoute: AdminRoadmapRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSponsorsRoute: AdminSponsorsRoute,
  AdminTeamRoute: AdminTeamRoute,
  AdminTractionRoute: AdminTractionRoute,
  StudentDashboardRoute: StudentDashboardRoute,
  StudentEventsRoute: StudentEventsRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentRegistrationsRoute: StudentRegistrationsRoute,
  StudentSettingsRoute: StudentSettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
